package org.yuexin.model;

import java.util.Date;

public class AppVersion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.id
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.vesion_code
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    private Integer vesionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.version_name
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    private String versionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.update_title
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    private String updateTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.url
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.add_time
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.sys_flag
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    private Byte sysFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.update_content
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    private String updateContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.id
     *
     * @return the value of app_version.id
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.id
     *
     * @param id the value for app_version.id
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.vesion_code
     *
     * @return the value of app_version.vesion_code
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    public Integer getVesionCode() {
        return vesionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.vesion_code
     *
     * @param vesionCode the value for app_version.vesion_code
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    public void setVesionCode(Integer vesionCode) {
        this.vesionCode = vesionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.version_name
     *
     * @return the value of app_version.version_name
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    public String getVersionName() {
        return versionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.version_name
     *
     * @param versionName the value for app_version.version_name
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    public void setVersionName(String versionName) {
        this.versionName = versionName == null ? null : versionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.update_title
     *
     * @return the value of app_version.update_title
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    public String getUpdateTitle() {
        return updateTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.update_title
     *
     * @param updateTitle the value for app_version.update_title
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    public void setUpdateTitle(String updateTitle) {
        this.updateTitle = updateTitle == null ? null : updateTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.url
     *
     * @return the value of app_version.url
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.url
     *
     * @param url the value for app_version.url
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.add_time
     *
     * @return the value of app_version.add_time
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.add_time
     *
     * @param addTime the value for app_version.add_time
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.sys_flag
     *
     * @return the value of app_version.sys_flag
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    public Byte getSysFlag() {
        return sysFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.sys_flag
     *
     * @param sysFlag the value for app_version.sys_flag
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    public void setSysFlag(Byte sysFlag) {
        this.sysFlag = sysFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.update_content
     *
     * @return the value of app_version.update_content
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    public String getUpdateContent() {
        return updateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.update_content
     *
     * @param updateContent the value for app_version.update_content
     *
     * @mbggenerated Thu Dec 22 11:34:18 CST 2016
     */
    public void setUpdateContent(String updateContent) {
        this.updateContent = updateContent == null ? null : updateContent.trim();
    }
}