package org.yuexin.model;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_no
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.vedio_id
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    private Integer vedioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.money
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_status
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    private Byte payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.add_time
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.sys_flag
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    private Byte sysFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_no
     *
     * @return the value of order.order_no
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_no
     *
     * @param orderNo the value for order.order_no
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.vedio_id
     *
     * @return the value of order.vedio_id
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    public Integer getVedioId() {
        return vedioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.vedio_id
     *
     * @param vedioId the value for order.vedio_id
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    public void setVedioId(Integer vedioId) {
        this.vedioId = vedioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.money
     *
     * @return the value of order.money
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.money
     *
     * @param money the value for order.money
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay_status
     *
     * @return the value of order.pay_status
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    public Byte getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay_status
     *
     * @param payStatus the value for order.pay_status
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    public void setPayStatus(Byte payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.add_time
     *
     * @return the value of order.add_time
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.add_time
     *
     * @param addTime the value for order.add_time
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.sys_flag
     *
     * @return the value of order.sys_flag
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    public Byte getSysFlag() {
        return sysFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.sys_flag
     *
     * @param sysFlag the value for order.sys_flag
     *
     * @mbggenerated Thu Jan 05 17:13:26 CST 2017
     */
    public void setSysFlag(Byte sysFlag) {
        this.sysFlag = sysFlag;
    }
}