package org.yuexin.model;

import java.util.Date;

public class PlayRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play_record.id
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play_record.user_id
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play_record.vedio_id
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    private Integer vedioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play_record.add_time
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play_record.sys_flag
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    private Byte sysFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play_record.id
     *
     * @return the value of play_record.id
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play_record.id
     *
     * @param id the value for play_record.id
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play_record.user_id
     *
     * @return the value of play_record.user_id
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play_record.user_id
     *
     * @param userId the value for play_record.user_id
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play_record.vedio_id
     *
     * @return the value of play_record.vedio_id
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    public Integer getVedioId() {
        return vedioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play_record.vedio_id
     *
     * @param vedioId the value for play_record.vedio_id
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    public void setVedioId(Integer vedioId) {
        this.vedioId = vedioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play_record.add_time
     *
     * @return the value of play_record.add_time
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play_record.add_time
     *
     * @param addTime the value for play_record.add_time
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play_record.sys_flag
     *
     * @return the value of play_record.sys_flag
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    public Byte getSysFlag() {
        return sysFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play_record.sys_flag
     *
     * @param sysFlag the value for play_record.sys_flag
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    public void setSysFlag(Byte sysFlag) {
        this.sysFlag = sysFlag;
    }
}