package org.yuexin.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public SysUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_user
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSysUserNameIsNull() {
            addCriterion("sys_user_name is null");
            return (Criteria) this;
        }

        public Criteria andSysUserNameIsNotNull() {
            addCriterion("sys_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andSysUserNameEqualTo(String value) {
            addCriterion("sys_user_name =", value, "sysUserName");
            return (Criteria) this;
        }

        public Criteria andSysUserNameNotEqualTo(String value) {
            addCriterion("sys_user_name <>", value, "sysUserName");
            return (Criteria) this;
        }

        public Criteria andSysUserNameGreaterThan(String value) {
            addCriterion("sys_user_name >", value, "sysUserName");
            return (Criteria) this;
        }

        public Criteria andSysUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("sys_user_name >=", value, "sysUserName");
            return (Criteria) this;
        }

        public Criteria andSysUserNameLessThan(String value) {
            addCriterion("sys_user_name <", value, "sysUserName");
            return (Criteria) this;
        }

        public Criteria andSysUserNameLessThanOrEqualTo(String value) {
            addCriterion("sys_user_name <=", value, "sysUserName");
            return (Criteria) this;
        }

        public Criteria andSysUserNameLike(String value) {
            addCriterion("sys_user_name like", value, "sysUserName");
            return (Criteria) this;
        }

        public Criteria andSysUserNameNotLike(String value) {
            addCriterion("sys_user_name not like", value, "sysUserName");
            return (Criteria) this;
        }

        public Criteria andSysUserNameIn(List<String> values) {
            addCriterion("sys_user_name in", values, "sysUserName");
            return (Criteria) this;
        }

        public Criteria andSysUserNameNotIn(List<String> values) {
            addCriterion("sys_user_name not in", values, "sysUserName");
            return (Criteria) this;
        }

        public Criteria andSysUserNameBetween(String value1, String value2) {
            addCriterion("sys_user_name between", value1, value2, "sysUserName");
            return (Criteria) this;
        }

        public Criteria andSysUserNameNotBetween(String value1, String value2) {
            addCriterion("sys_user_name not between", value1, value2, "sysUserName");
            return (Criteria) this;
        }

        public Criteria andSysRealNameIsNull() {
            addCriterion("sys_real_name is null");
            return (Criteria) this;
        }

        public Criteria andSysRealNameIsNotNull() {
            addCriterion("sys_real_name is not null");
            return (Criteria) this;
        }

        public Criteria andSysRealNameEqualTo(String value) {
            addCriterion("sys_real_name =", value, "sysRealName");
            return (Criteria) this;
        }

        public Criteria andSysRealNameNotEqualTo(String value) {
            addCriterion("sys_real_name <>", value, "sysRealName");
            return (Criteria) this;
        }

        public Criteria andSysRealNameGreaterThan(String value) {
            addCriterion("sys_real_name >", value, "sysRealName");
            return (Criteria) this;
        }

        public Criteria andSysRealNameGreaterThanOrEqualTo(String value) {
            addCriterion("sys_real_name >=", value, "sysRealName");
            return (Criteria) this;
        }

        public Criteria andSysRealNameLessThan(String value) {
            addCriterion("sys_real_name <", value, "sysRealName");
            return (Criteria) this;
        }

        public Criteria andSysRealNameLessThanOrEqualTo(String value) {
            addCriterion("sys_real_name <=", value, "sysRealName");
            return (Criteria) this;
        }

        public Criteria andSysRealNameLike(String value) {
            addCriterion("sys_real_name like", value, "sysRealName");
            return (Criteria) this;
        }

        public Criteria andSysRealNameNotLike(String value) {
            addCriterion("sys_real_name not like", value, "sysRealName");
            return (Criteria) this;
        }

        public Criteria andSysRealNameIn(List<String> values) {
            addCriterion("sys_real_name in", values, "sysRealName");
            return (Criteria) this;
        }

        public Criteria andSysRealNameNotIn(List<String> values) {
            addCriterion("sys_real_name not in", values, "sysRealName");
            return (Criteria) this;
        }

        public Criteria andSysRealNameBetween(String value1, String value2) {
            addCriterion("sys_real_name between", value1, value2, "sysRealName");
            return (Criteria) this;
        }

        public Criteria andSysRealNameNotBetween(String value1, String value2) {
            addCriterion("sys_real_name not between", value1, value2, "sysRealName");
            return (Criteria) this;
        }

        public Criteria andSysUserPasswordIsNull() {
            addCriterion("sys_user_password is null");
            return (Criteria) this;
        }

        public Criteria andSysUserPasswordIsNotNull() {
            addCriterion("sys_user_password is not null");
            return (Criteria) this;
        }

        public Criteria andSysUserPasswordEqualTo(String value) {
            addCriterion("sys_user_password =", value, "sysUserPassword");
            return (Criteria) this;
        }

        public Criteria andSysUserPasswordNotEqualTo(String value) {
            addCriterion("sys_user_password <>", value, "sysUserPassword");
            return (Criteria) this;
        }

        public Criteria andSysUserPasswordGreaterThan(String value) {
            addCriterion("sys_user_password >", value, "sysUserPassword");
            return (Criteria) this;
        }

        public Criteria andSysUserPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("sys_user_password >=", value, "sysUserPassword");
            return (Criteria) this;
        }

        public Criteria andSysUserPasswordLessThan(String value) {
            addCriterion("sys_user_password <", value, "sysUserPassword");
            return (Criteria) this;
        }

        public Criteria andSysUserPasswordLessThanOrEqualTo(String value) {
            addCriterion("sys_user_password <=", value, "sysUserPassword");
            return (Criteria) this;
        }

        public Criteria andSysUserPasswordLike(String value) {
            addCriterion("sys_user_password like", value, "sysUserPassword");
            return (Criteria) this;
        }

        public Criteria andSysUserPasswordNotLike(String value) {
            addCriterion("sys_user_password not like", value, "sysUserPassword");
            return (Criteria) this;
        }

        public Criteria andSysUserPasswordIn(List<String> values) {
            addCriterion("sys_user_password in", values, "sysUserPassword");
            return (Criteria) this;
        }

        public Criteria andSysUserPasswordNotIn(List<String> values) {
            addCriterion("sys_user_password not in", values, "sysUserPassword");
            return (Criteria) this;
        }

        public Criteria andSysUserPasswordBetween(String value1, String value2) {
            addCriterion("sys_user_password between", value1, value2, "sysUserPassword");
            return (Criteria) this;
        }

        public Criteria andSysUserPasswordNotBetween(String value1, String value2) {
            addCriterion("sys_user_password not between", value1, value2, "sysUserPassword");
            return (Criteria) this;
        }

        public Criteria andSysPhoneIsNull() {
            addCriterion("sys_phone is null");
            return (Criteria) this;
        }

        public Criteria andSysPhoneIsNotNull() {
            addCriterion("sys_phone is not null");
            return (Criteria) this;
        }

        public Criteria andSysPhoneEqualTo(String value) {
            addCriterion("sys_phone =", value, "sysPhone");
            return (Criteria) this;
        }

        public Criteria andSysPhoneNotEqualTo(String value) {
            addCriterion("sys_phone <>", value, "sysPhone");
            return (Criteria) this;
        }

        public Criteria andSysPhoneGreaterThan(String value) {
            addCriterion("sys_phone >", value, "sysPhone");
            return (Criteria) this;
        }

        public Criteria andSysPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("sys_phone >=", value, "sysPhone");
            return (Criteria) this;
        }

        public Criteria andSysPhoneLessThan(String value) {
            addCriterion("sys_phone <", value, "sysPhone");
            return (Criteria) this;
        }

        public Criteria andSysPhoneLessThanOrEqualTo(String value) {
            addCriterion("sys_phone <=", value, "sysPhone");
            return (Criteria) this;
        }

        public Criteria andSysPhoneLike(String value) {
            addCriterion("sys_phone like", value, "sysPhone");
            return (Criteria) this;
        }

        public Criteria andSysPhoneNotLike(String value) {
            addCriterion("sys_phone not like", value, "sysPhone");
            return (Criteria) this;
        }

        public Criteria andSysPhoneIn(List<String> values) {
            addCriterion("sys_phone in", values, "sysPhone");
            return (Criteria) this;
        }

        public Criteria andSysPhoneNotIn(List<String> values) {
            addCriterion("sys_phone not in", values, "sysPhone");
            return (Criteria) this;
        }

        public Criteria andSysPhoneBetween(String value1, String value2) {
            addCriterion("sys_phone between", value1, value2, "sysPhone");
            return (Criteria) this;
        }

        public Criteria andSysPhoneNotBetween(String value1, String value2) {
            addCriterion("sys_phone not between", value1, value2, "sysPhone");
            return (Criteria) this;
        }

        public Criteria andFaceImgUrlIsNull() {
            addCriterion("face_img_url is null");
            return (Criteria) this;
        }

        public Criteria andFaceImgUrlIsNotNull() {
            addCriterion("face_img_url is not null");
            return (Criteria) this;
        }

        public Criteria andFaceImgUrlEqualTo(String value) {
            addCriterion("face_img_url =", value, "faceImgUrl");
            return (Criteria) this;
        }

        public Criteria andFaceImgUrlNotEqualTo(String value) {
            addCriterion("face_img_url <>", value, "faceImgUrl");
            return (Criteria) this;
        }

        public Criteria andFaceImgUrlGreaterThan(String value) {
            addCriterion("face_img_url >", value, "faceImgUrl");
            return (Criteria) this;
        }

        public Criteria andFaceImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("face_img_url >=", value, "faceImgUrl");
            return (Criteria) this;
        }

        public Criteria andFaceImgUrlLessThan(String value) {
            addCriterion("face_img_url <", value, "faceImgUrl");
            return (Criteria) this;
        }

        public Criteria andFaceImgUrlLessThanOrEqualTo(String value) {
            addCriterion("face_img_url <=", value, "faceImgUrl");
            return (Criteria) this;
        }

        public Criteria andFaceImgUrlLike(String value) {
            addCriterion("face_img_url like", value, "faceImgUrl");
            return (Criteria) this;
        }

        public Criteria andFaceImgUrlNotLike(String value) {
            addCriterion("face_img_url not like", value, "faceImgUrl");
            return (Criteria) this;
        }

        public Criteria andFaceImgUrlIn(List<String> values) {
            addCriterion("face_img_url in", values, "faceImgUrl");
            return (Criteria) this;
        }

        public Criteria andFaceImgUrlNotIn(List<String> values) {
            addCriterion("face_img_url not in", values, "faceImgUrl");
            return (Criteria) this;
        }

        public Criteria andFaceImgUrlBetween(String value1, String value2) {
            addCriterion("face_img_url between", value1, value2, "faceImgUrl");
            return (Criteria) this;
        }

        public Criteria andFaceImgUrlNotBetween(String value1, String value2) {
            addCriterion("face_img_url not between", value1, value2, "faceImgUrl");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andSysFlagIsNull() {
            addCriterion("sys_flag is null");
            return (Criteria) this;
        }

        public Criteria andSysFlagIsNotNull() {
            addCriterion("sys_flag is not null");
            return (Criteria) this;
        }

        public Criteria andSysFlagEqualTo(Byte value) {
            addCriterion("sys_flag =", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagNotEqualTo(Byte value) {
            addCriterion("sys_flag <>", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagGreaterThan(Byte value) {
            addCriterion("sys_flag >", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagGreaterThanOrEqualTo(Byte value) {
            addCriterion("sys_flag >=", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagLessThan(Byte value) {
            addCriterion("sys_flag <", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagLessThanOrEqualTo(Byte value) {
            addCriterion("sys_flag <=", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagIn(List<Byte> values) {
            addCriterion("sys_flag in", values, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagNotIn(List<Byte> values) {
            addCriterion("sys_flag not in", values, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagBetween(Byte value1, Byte value2) {
            addCriterion("sys_flag between", value1, value2, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagNotBetween(Byte value1, Byte value2) {
            addCriterion("sys_flag not between", value1, value2, "sysFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_user
     *
     * @mbggenerated do_not_delete_during_merge Fri Dec 09 15:36:35 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_user
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}