package org.yuexin.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.real_name
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.face_img_url
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private String faceImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.religious_belief
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Integer religiousBelief;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.add_time
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sys_flag
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Byte sysFlag;

    /**
     * 年龄
     */
    private int age;

    /**
     * 工作
     */
    private String job;

    /**
     * 短信验证码
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.real_name
     *
     * @return the value of user.real_name
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.real_name
     *
     * @param realName the value for user.real_name
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.face_img_url
     *
     * @return the value of user.face_img_url
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public String getFaceImgUrl() {
        return faceImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.face_img_url
     *
     * @param faceImgUrl the value for user.face_img_url
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setFaceImgUrl(String faceImgUrl) {
        this.faceImgUrl = faceImgUrl == null ? null : faceImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.religious_belief
     *
     * @return the value of user.religious_belief
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Integer getReligiousBelief() {
        return religiousBelief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.religious_belief
     *
     * @param religiousBelief the value for user.religious_belief
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setReligiousBelief(Integer religiousBelief) {
        this.religiousBelief = religiousBelief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.add_time
     *
     * @return the value of user.add_time
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.add_time
     *
     * @param addTime the value for user.add_time
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sys_flag
     *
     * @return the value of user.sys_flag
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Byte getSysFlag() {
        return sysFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sys_flag
     *
     * @param sysFlag the value for user.sys_flag
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setSysFlag(Byte sysFlag) {
        this.sysFlag = sysFlag;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getJob() {
        return job;
    }

    public void setJob(String job) {
        this.job = job;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }
}