package org.yuexin.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VedioExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vedio
     *
     * @mbggenerated Wed Dec 14 10:25:31 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vedio
     *
     * @mbggenerated Wed Dec 14 10:25:31 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vedio
     *
     * @mbggenerated Wed Dec 14 10:25:31 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio
     *
     * @mbggenerated Wed Dec 14 10:25:31 CST 2016
     */
    public VedioExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio
     *
     * @mbggenerated Wed Dec 14 10:25:31 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio
     *
     * @mbggenerated Wed Dec 14 10:25:31 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio
     *
     * @mbggenerated Wed Dec 14 10:25:31 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio
     *
     * @mbggenerated Wed Dec 14 10:25:31 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio
     *
     * @mbggenerated Wed Dec 14 10:25:31 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio
     *
     * @mbggenerated Wed Dec 14 10:25:31 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio
     *
     * @mbggenerated Wed Dec 14 10:25:31 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio
     *
     * @mbggenerated Wed Dec 14 10:25:31 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio
     *
     * @mbggenerated Wed Dec 14 10:25:31 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio
     *
     * @mbggenerated Wed Dec 14 10:25:31 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vedio
     *
     * @mbggenerated Wed Dec 14 10:25:31 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryIdIsNull() {
            addCriterion("vedio_category_id is null");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryIdIsNotNull() {
            addCriterion("vedio_category_id is not null");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryIdEqualTo(Integer value) {
            addCriterion("vedio_category_id =", value, "vedioCategoryId");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryIdNotEqualTo(Integer value) {
            addCriterion("vedio_category_id <>", value, "vedioCategoryId");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryIdGreaterThan(Integer value) {
            addCriterion("vedio_category_id >", value, "vedioCategoryId");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vedio_category_id >=", value, "vedioCategoryId");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryIdLessThan(Integer value) {
            addCriterion("vedio_category_id <", value, "vedioCategoryId");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryIdLessThanOrEqualTo(Integer value) {
            addCriterion("vedio_category_id <=", value, "vedioCategoryId");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryIdIn(List<Integer> values) {
            addCriterion("vedio_category_id in", values, "vedioCategoryId");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryIdNotIn(List<Integer> values) {
            addCriterion("vedio_category_id not in", values, "vedioCategoryId");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryIdBetween(Integer value1, Integer value2) {
            addCriterion("vedio_category_id between", value1, value2, "vedioCategoryId");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vedio_category_id not between", value1, value2, "vedioCategoryId");
            return (Criteria) this;
        }

        public Criteria andIsFreeIsNull() {
            addCriterion("is_free is null");
            return (Criteria) this;
        }

        public Criteria andIsFreeIsNotNull() {
            addCriterion("is_free is not null");
            return (Criteria) this;
        }

        public Criteria andIsFreeEqualTo(Short value) {
            addCriterion("is_free =", value, "isFree");
            return (Criteria) this;
        }

        public Criteria andIsFreeNotEqualTo(Short value) {
            addCriterion("is_free <>", value, "isFree");
            return (Criteria) this;
        }

        public Criteria andIsFreeGreaterThan(Short value) {
            addCriterion("is_free >", value, "isFree");
            return (Criteria) this;
        }

        public Criteria andIsFreeGreaterThanOrEqualTo(Short value) {
            addCriterion("is_free >=", value, "isFree");
            return (Criteria) this;
        }

        public Criteria andIsFreeLessThan(Short value) {
            addCriterion("is_free <", value, "isFree");
            return (Criteria) this;
        }

        public Criteria andIsFreeLessThanOrEqualTo(Short value) {
            addCriterion("is_free <=", value, "isFree");
            return (Criteria) this;
        }

        public Criteria andIsFreeIn(List<Short> values) {
            addCriterion("is_free in", values, "isFree");
            return (Criteria) this;
        }

        public Criteria andIsFreeNotIn(List<Short> values) {
            addCriterion("is_free not in", values, "isFree");
            return (Criteria) this;
        }

        public Criteria andIsFreeBetween(Short value1, Short value2) {
            addCriterion("is_free between", value1, value2, "isFree");
            return (Criteria) this;
        }

        public Criteria andIsFreeNotBetween(Short value1, Short value2) {
            addCriterion("is_free not between", value1, value2, "isFree");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNull() {
            addCriterion("money is null");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNotNull() {
            addCriterion("money is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyEqualTo(Integer value) {
            addCriterion("money =", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotEqualTo(Integer value) {
            addCriterion("money <>", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThan(Integer value) {
            addCriterion("money >", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThanOrEqualTo(Integer value) {
            addCriterion("money >=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThan(Integer value) {
            addCriterion("money <", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThanOrEqualTo(Integer value) {
            addCriterion("money <=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyIn(List<Integer> values) {
            addCriterion("money in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotIn(List<Integer> values) {
            addCriterion("money not in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyBetween(Integer value1, Integer value2) {
            addCriterion("money between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotBetween(Integer value1, Integer value2) {
            addCriterion("money not between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andVedioNameIsNull() {
            addCriterion("vedio_name is null");
            return (Criteria) this;
        }

        public Criteria andVedioNameIsNotNull() {
            addCriterion("vedio_name is not null");
            return (Criteria) this;
        }

        public Criteria andVedioNameEqualTo(String value) {
            addCriterion("vedio_name =", value, "vedioName");
            return (Criteria) this;
        }

        public Criteria andVedioNameNotEqualTo(String value) {
            addCriterion("vedio_name <>", value, "vedioName");
            return (Criteria) this;
        }

        public Criteria andVedioNameGreaterThan(String value) {
            addCriterion("vedio_name >", value, "vedioName");
            return (Criteria) this;
        }

        public Criteria andVedioNameGreaterThanOrEqualTo(String value) {
            addCriterion("vedio_name >=", value, "vedioName");
            return (Criteria) this;
        }

        public Criteria andVedioNameLessThan(String value) {
            addCriterion("vedio_name <", value, "vedioName");
            return (Criteria) this;
        }

        public Criteria andVedioNameLessThanOrEqualTo(String value) {
            addCriterion("vedio_name <=", value, "vedioName");
            return (Criteria) this;
        }

        public Criteria andVedioNameLike(String value) {
            addCriterion("vedio_name like", value, "vedioName");
            return (Criteria) this;
        }

        public Criteria andVedioNameNotLike(String value) {
            addCriterion("vedio_name not like", value, "vedioName");
            return (Criteria) this;
        }

        public Criteria andVedioNameIn(List<String> values) {
            addCriterion("vedio_name in", values, "vedioName");
            return (Criteria) this;
        }

        public Criteria andVedioNameNotIn(List<String> values) {
            addCriterion("vedio_name not in", values, "vedioName");
            return (Criteria) this;
        }

        public Criteria andVedioNameBetween(String value1, String value2) {
            addCriterion("vedio_name between", value1, value2, "vedioName");
            return (Criteria) this;
        }

        public Criteria andVedioNameNotBetween(String value1, String value2) {
            addCriterion("vedio_name not between", value1, value2, "vedioName");
            return (Criteria) this;
        }

        public Criteria andVedioImgUrlIsNull() {
            addCriterion("vedio_img_url is null");
            return (Criteria) this;
        }

        public Criteria andVedioImgUrlIsNotNull() {
            addCriterion("vedio_img_url is not null");
            return (Criteria) this;
        }

        public Criteria andVedioImgUrlEqualTo(String value) {
            addCriterion("vedio_img_url =", value, "vedioImgUrl");
            return (Criteria) this;
        }

        public Criteria andVedioImgUrlNotEqualTo(String value) {
            addCriterion("vedio_img_url <>", value, "vedioImgUrl");
            return (Criteria) this;
        }

        public Criteria andVedioImgUrlGreaterThan(String value) {
            addCriterion("vedio_img_url >", value, "vedioImgUrl");
            return (Criteria) this;
        }

        public Criteria andVedioImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("vedio_img_url >=", value, "vedioImgUrl");
            return (Criteria) this;
        }

        public Criteria andVedioImgUrlLessThan(String value) {
            addCriterion("vedio_img_url <", value, "vedioImgUrl");
            return (Criteria) this;
        }

        public Criteria andVedioImgUrlLessThanOrEqualTo(String value) {
            addCriterion("vedio_img_url <=", value, "vedioImgUrl");
            return (Criteria) this;
        }

        public Criteria andVedioImgUrlLike(String value) {
            addCriterion("vedio_img_url like", value, "vedioImgUrl");
            return (Criteria) this;
        }

        public Criteria andVedioImgUrlNotLike(String value) {
            addCriterion("vedio_img_url not like", value, "vedioImgUrl");
            return (Criteria) this;
        }

        public Criteria andVedioImgUrlIn(List<String> values) {
            addCriterion("vedio_img_url in", values, "vedioImgUrl");
            return (Criteria) this;
        }

        public Criteria andVedioImgUrlNotIn(List<String> values) {
            addCriterion("vedio_img_url not in", values, "vedioImgUrl");
            return (Criteria) this;
        }

        public Criteria andVedioImgUrlBetween(String value1, String value2) {
            addCriterion("vedio_img_url between", value1, value2, "vedioImgUrl");
            return (Criteria) this;
        }

        public Criteria andVedioImgUrlNotBetween(String value1, String value2) {
            addCriterion("vedio_img_url not between", value1, value2, "vedioImgUrl");
            return (Criteria) this;
        }

        public Criteria andVedioUrlIsNull() {
            addCriterion("vedio_url is null");
            return (Criteria) this;
        }

        public Criteria andVedioUrlIsNotNull() {
            addCriterion("vedio_url is not null");
            return (Criteria) this;
        }

        public Criteria andVedioUrlEqualTo(String value) {
            addCriterion("vedio_url =", value, "vedioUrl");
            return (Criteria) this;
        }

        public Criteria andVedioUrlNotEqualTo(String value) {
            addCriterion("vedio_url <>", value, "vedioUrl");
            return (Criteria) this;
        }

        public Criteria andVedioUrlGreaterThan(String value) {
            addCriterion("vedio_url >", value, "vedioUrl");
            return (Criteria) this;
        }

        public Criteria andVedioUrlGreaterThanOrEqualTo(String value) {
            addCriterion("vedio_url >=", value, "vedioUrl");
            return (Criteria) this;
        }

        public Criteria andVedioUrlLessThan(String value) {
            addCriterion("vedio_url <", value, "vedioUrl");
            return (Criteria) this;
        }

        public Criteria andVedioUrlLessThanOrEqualTo(String value) {
            addCriterion("vedio_url <=", value, "vedioUrl");
            return (Criteria) this;
        }

        public Criteria andVedioUrlLike(String value) {
            addCriterion("vedio_url like", value, "vedioUrl");
            return (Criteria) this;
        }

        public Criteria andVedioUrlNotLike(String value) {
            addCriterion("vedio_url not like", value, "vedioUrl");
            return (Criteria) this;
        }

        public Criteria andVedioUrlIn(List<String> values) {
            addCriterion("vedio_url in", values, "vedioUrl");
            return (Criteria) this;
        }

        public Criteria andVedioUrlNotIn(List<String> values) {
            addCriterion("vedio_url not in", values, "vedioUrl");
            return (Criteria) this;
        }

        public Criteria andVedioUrlBetween(String value1, String value2) {
            addCriterion("vedio_url between", value1, value2, "vedioUrl");
            return (Criteria) this;
        }

        public Criteria andVedioUrlNotBetween(String value1, String value2) {
            addCriterion("vedio_url not between", value1, value2, "vedioUrl");
            return (Criteria) this;
        }

        public Criteria andVedioStatusIsNull() {
            addCriterion("vedio_status is null");
            return (Criteria) this;
        }

        public Criteria andVedioStatusIsNotNull() {
            addCriterion("vedio_status is not null");
            return (Criteria) this;
        }

        public Criteria andVedioStatusEqualTo(Integer value) {
            addCriterion("vedio_status =", value, "vedioStatus");
            return (Criteria) this;
        }

        public Criteria andVedioStatusNotEqualTo(Integer value) {
            addCriterion("vedio_status <>", value, "vedioStatus");
            return (Criteria) this;
        }

        public Criteria andVedioStatusGreaterThan(Integer value) {
            addCriterion("vedio_status >", value, "vedioStatus");
            return (Criteria) this;
        }

        public Criteria andVedioStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("vedio_status >=", value, "vedioStatus");
            return (Criteria) this;
        }

        public Criteria andVedioStatusLessThan(Integer value) {
            addCriterion("vedio_status <", value, "vedioStatus");
            return (Criteria) this;
        }

        public Criteria andVedioStatusLessThanOrEqualTo(Integer value) {
            addCriterion("vedio_status <=", value, "vedioStatus");
            return (Criteria) this;
        }

        public Criteria andVedioStatusIn(List<Integer> values) {
            addCriterion("vedio_status in", values, "vedioStatus");
            return (Criteria) this;
        }

        public Criteria andVedioStatusNotIn(List<Integer> values) {
            addCriterion("vedio_status not in", values, "vedioStatus");
            return (Criteria) this;
        }

        public Criteria andVedioStatusBetween(Integer value1, Integer value2) {
            addCriterion("vedio_status between", value1, value2, "vedioStatus");
            return (Criteria) this;
        }

        public Criteria andVedioStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("vedio_status not between", value1, value2, "vedioStatus");
            return (Criteria) this;
        }

        public Criteria andPlayAmountIsNull() {
            addCriterion("play_amount is null");
            return (Criteria) this;
        }

        public Criteria andPlayAmountIsNotNull() {
            addCriterion("play_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPlayAmountEqualTo(Integer value) {
            addCriterion("play_amount =", value, "playAmount");
            return (Criteria) this;
        }

        public Criteria andPlayAmountNotEqualTo(Integer value) {
            addCriterion("play_amount <>", value, "playAmount");
            return (Criteria) this;
        }

        public Criteria andPlayAmountGreaterThan(Integer value) {
            addCriterion("play_amount >", value, "playAmount");
            return (Criteria) this;
        }

        public Criteria andPlayAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("play_amount >=", value, "playAmount");
            return (Criteria) this;
        }

        public Criteria andPlayAmountLessThan(Integer value) {
            addCriterion("play_amount <", value, "playAmount");
            return (Criteria) this;
        }

        public Criteria andPlayAmountLessThanOrEqualTo(Integer value) {
            addCriterion("play_amount <=", value, "playAmount");
            return (Criteria) this;
        }

        public Criteria andPlayAmountIn(List<Integer> values) {
            addCriterion("play_amount in", values, "playAmount");
            return (Criteria) this;
        }

        public Criteria andPlayAmountNotIn(List<Integer> values) {
            addCriterion("play_amount not in", values, "playAmount");
            return (Criteria) this;
        }

        public Criteria andPlayAmountBetween(Integer value1, Integer value2) {
            addCriterion("play_amount between", value1, value2, "playAmount");
            return (Criteria) this;
        }

        public Criteria andPlayAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("play_amount not between", value1, value2, "playAmount");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andSysFlagIsNull() {
            addCriterion("sys_flag is null");
            return (Criteria) this;
        }

        public Criteria andSysFlagIsNotNull() {
            addCriterion("sys_flag is not null");
            return (Criteria) this;
        }

        public Criteria andSysFlagEqualTo(Byte value) {
            addCriterion("sys_flag =", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagNotEqualTo(Byte value) {
            addCriterion("sys_flag <>", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagGreaterThan(Byte value) {
            addCriterion("sys_flag >", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagGreaterThanOrEqualTo(Byte value) {
            addCriterion("sys_flag >=", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagLessThan(Byte value) {
            addCriterion("sys_flag <", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagLessThanOrEqualTo(Byte value) {
            addCriterion("sys_flag <=", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagIn(List<Byte> values) {
            addCriterion("sys_flag in", values, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagNotIn(List<Byte> values) {
            addCriterion("sys_flag not in", values, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagBetween(Byte value1, Byte value2) {
            addCriterion("sys_flag between", value1, value2, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagNotBetween(Byte value1, Byte value2) {
            addCriterion("sys_flag not between", value1, value2, "sysFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vedio
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 14 10:25:31 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vedio
     *
     * @mbggenerated Wed Dec 14 10:25:31 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}