package org.yuexin.model;

import java.util.Date;

public class Vedio {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio.id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio.vedio_category_id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Integer vedioCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio.is_free
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Short isFree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio.money
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio.vedio_name
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private String vedioName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio.vedio_img_url
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private String vedioImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio.vedio_url
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private String vedioUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio.vedio_status
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Integer vedioStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio.play_amount
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Integer playAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio.add_time
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio.sys_flag
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Byte sysFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio.vedio_notes
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private String vedioNotes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio.id
     *
     * @return the value of vedio.id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio.id
     *
     * @param id the value for vedio.id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio.vedio_category_id
     *
     * @return the value of vedio.vedio_category_id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Integer getVedioCategoryId() {
        return vedioCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio.vedio_category_id
     *
     * @param vedioCategoryId the value for vedio.vedio_category_id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setVedioCategoryId(Integer vedioCategoryId) {
        this.vedioCategoryId = vedioCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio.is_free
     *
     * @return the value of vedio.is_free
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Short getIsFree() {
        return isFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio.is_free
     *
     * @param isFree the value for vedio.is_free
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setIsFree(Short isFree) {
        this.isFree = isFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio.money
     *
     * @return the value of vedio.money
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio.money
     *
     * @param money the value for vedio.money
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio.vedio_name
     *
     * @return the value of vedio.vedio_name
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public String getVedioName() {
        return vedioName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio.vedio_name
     *
     * @param vedioName the value for vedio.vedio_name
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setVedioName(String vedioName) {
        this.vedioName = vedioName == null ? null : vedioName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio.vedio_img_url
     *
     * @return the value of vedio.vedio_img_url
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public String getVedioImgUrl() {
        return vedioImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio.vedio_img_url
     *
     * @param vedioImgUrl the value for vedio.vedio_img_url
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setVedioImgUrl(String vedioImgUrl) {
        this.vedioImgUrl = vedioImgUrl == null ? null : vedioImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio.vedio_url
     *
     * @return the value of vedio.vedio_url
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public String getVedioUrl() {
        return vedioUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio.vedio_url
     *
     * @param vedioUrl the value for vedio.vedio_url
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setVedioUrl(String vedioUrl) {
        this.vedioUrl = vedioUrl == null ? null : vedioUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio.vedio_status
     *
     * @return the value of vedio.vedio_status
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Integer getVedioStatus() {
        return vedioStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio.vedio_status
     *
     * @param vedioStatus the value for vedio.vedio_status
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setVedioStatus(Integer vedioStatus) {
        this.vedioStatus = vedioStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio.play_amount
     *
     * @return the value of vedio.play_amount
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Integer getPlayAmount() {
        return playAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio.play_amount
     *
     * @param playAmount the value for vedio.play_amount
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setPlayAmount(Integer playAmount) {
        this.playAmount = playAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio.add_time
     *
     * @return the value of vedio.add_time
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio.add_time
     *
     * @param addTime the value for vedio.add_time
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio.sys_flag
     *
     * @return the value of vedio.sys_flag
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Byte getSysFlag() {
        return sysFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio.sys_flag
     *
     * @param sysFlag the value for vedio.sys_flag
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setSysFlag(Byte sysFlag) {
        this.sysFlag = sysFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio.vedio_notes
     *
     * @return the value of vedio.vedio_notes
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public String getVedioNotes() {
        return vedioNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio.vedio_notes
     *
     * @param vedioNotes the value for vedio.vedio_notes
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setVedioNotes(String vedioNotes) {
        this.vedioNotes = vedioNotes == null ? null : vedioNotes.trim();
    }
}