package org.yuexin.model;

import java.util.Date;

public class VedioLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio_log.id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio_log.sys_user_id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Integer sysUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio_log.vedio_id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Integer vedioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio_log.add_time
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio_log.sys_flag
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Byte sysFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio_log.id
     *
     * @return the value of vedio_log.id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio_log.id
     *
     * @param id the value for vedio_log.id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio_log.sys_user_id
     *
     * @return the value of vedio_log.sys_user_id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Integer getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio_log.sys_user_id
     *
     * @param sysUserId the value for vedio_log.sys_user_id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setSysUserId(Integer sysUserId) {
        this.sysUserId = sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio_log.vedio_id
     *
     * @return the value of vedio_log.vedio_id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Integer getVedioId() {
        return vedioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio_log.vedio_id
     *
     * @param vedioId the value for vedio_log.vedio_id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setVedioId(Integer vedioId) {
        this.vedioId = vedioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio_log.add_time
     *
     * @return the value of vedio_log.add_time
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio_log.add_time
     *
     * @param addTime the value for vedio_log.add_time
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio_log.sys_flag
     *
     * @return the value of vedio_log.sys_flag
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Byte getSysFlag() {
        return sysFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio_log.sys_flag
     *
     * @param sysFlag the value for vedio_log.sys_flag
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setSysFlag(Byte sysFlag) {
        this.sysFlag = sysFlag;
    }
}