package org.yuexin.model;

import java.util.Date;

public class VedioCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio_category.id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio_category.p_id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Integer pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio_category.vedio_category_name
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private String vedioCategoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio_category.add_time
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio_category.update_time
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vedio_category.sys_flag
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    private Byte sysFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio_category.id
     *
     * @return the value of vedio_category.id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio_category.id
     *
     * @param id the value for vedio_category.id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio_category.p_id
     *
     * @return the value of vedio_category.p_id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio_category.p_id
     *
     * @param pId the value for vedio_category.p_id
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio_category.vedio_category_name
     *
     * @return the value of vedio_category.vedio_category_name
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public String getVedioCategoryName() {
        return vedioCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio_category.vedio_category_name
     *
     * @param vedioCategoryName the value for vedio_category.vedio_category_name
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setVedioCategoryName(String vedioCategoryName) {
        this.vedioCategoryName = vedioCategoryName == null ? null : vedioCategoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio_category.add_time
     *
     * @return the value of vedio_category.add_time
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio_category.add_time
     *
     * @param addTime the value for vedio_category.add_time
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio_category.update_time
     *
     * @return the value of vedio_category.update_time
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio_category.update_time
     *
     * @param updateTime the value for vedio_category.update_time
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vedio_category.sys_flag
     *
     * @return the value of vedio_category.sys_flag
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public Byte getSysFlag() {
        return sysFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vedio_category.sys_flag
     *
     * @param sysFlag the value for vedio_category.sys_flag
     *
     * @mbggenerated Fri Dec 09 15:36:35 CST 2016
     */
    public void setSysFlag(Byte sysFlag) {
        this.sysFlag = sysFlag;
    }
}