package org.yuexin.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VedioCategoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    public VedioCategoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPIdIsNull() {
            addCriterion("p_id is null");
            return (Criteria) this;
        }

        public Criteria andPIdIsNotNull() {
            addCriterion("p_id is not null");
            return (Criteria) this;
        }

        public Criteria andPIdEqualTo(Integer value) {
            addCriterion("p_id =", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdNotEqualTo(Integer value) {
            addCriterion("p_id <>", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdGreaterThan(Integer value) {
            addCriterion("p_id >", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_id >=", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdLessThan(Integer value) {
            addCriterion("p_id <", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdLessThanOrEqualTo(Integer value) {
            addCriterion("p_id <=", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdIn(List<Integer> values) {
            addCriterion("p_id in", values, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdNotIn(List<Integer> values) {
            addCriterion("p_id not in", values, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdBetween(Integer value1, Integer value2) {
            addCriterion("p_id between", value1, value2, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdNotBetween(Integer value1, Integer value2) {
            addCriterion("p_id not between", value1, value2, "pId");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryNameIsNull() {
            addCriterion("vedio_category_name is null");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryNameIsNotNull() {
            addCriterion("vedio_category_name is not null");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryNameEqualTo(String value) {
            addCriterion("vedio_category_name =", value, "vedioCategoryName");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryNameNotEqualTo(String value) {
            addCriterion("vedio_category_name <>", value, "vedioCategoryName");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryNameGreaterThan(String value) {
            addCriterion("vedio_category_name >", value, "vedioCategoryName");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryNameGreaterThanOrEqualTo(String value) {
            addCriterion("vedio_category_name >=", value, "vedioCategoryName");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryNameLessThan(String value) {
            addCriterion("vedio_category_name <", value, "vedioCategoryName");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryNameLessThanOrEqualTo(String value) {
            addCriterion("vedio_category_name <=", value, "vedioCategoryName");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryNameLike(String value) {
            addCriterion("vedio_category_name like", value, "vedioCategoryName");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryNameNotLike(String value) {
            addCriterion("vedio_category_name not like", value, "vedioCategoryName");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryNameIn(List<String> values) {
            addCriterion("vedio_category_name in", values, "vedioCategoryName");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryNameNotIn(List<String> values) {
            addCriterion("vedio_category_name not in", values, "vedioCategoryName");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryNameBetween(String value1, String value2) {
            addCriterion("vedio_category_name between", value1, value2, "vedioCategoryName");
            return (Criteria) this;
        }

        public Criteria andVedioCategoryNameNotBetween(String value1, String value2) {
            addCriterion("vedio_category_name not between", value1, value2, "vedioCategoryName");
            return (Criteria) this;
        }

        public Criteria andSmallLogoImgUrlIsNull() {
            addCriterion("small_logo_img_url is null");
            return (Criteria) this;
        }

        public Criteria andSmallLogoImgUrlIsNotNull() {
            addCriterion("small_logo_img_url is not null");
            return (Criteria) this;
        }

        public Criteria andSmallLogoImgUrlEqualTo(String value) {
            addCriterion("small_logo_img_url =", value, "smallLogoImgUrl");
            return (Criteria) this;
        }

        public Criteria andSmallLogoImgUrlNotEqualTo(String value) {
            addCriterion("small_logo_img_url <>", value, "smallLogoImgUrl");
            return (Criteria) this;
        }

        public Criteria andSmallLogoImgUrlGreaterThan(String value) {
            addCriterion("small_logo_img_url >", value, "smallLogoImgUrl");
            return (Criteria) this;
        }

        public Criteria andSmallLogoImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("small_logo_img_url >=", value, "smallLogoImgUrl");
            return (Criteria) this;
        }

        public Criteria andSmallLogoImgUrlLessThan(String value) {
            addCriterion("small_logo_img_url <", value, "smallLogoImgUrl");
            return (Criteria) this;
        }

        public Criteria andSmallLogoImgUrlLessThanOrEqualTo(String value) {
            addCriterion("small_logo_img_url <=", value, "smallLogoImgUrl");
            return (Criteria) this;
        }

        public Criteria andSmallLogoImgUrlLike(String value) {
            addCriterion("small_logo_img_url like", value, "smallLogoImgUrl");
            return (Criteria) this;
        }

        public Criteria andSmallLogoImgUrlNotLike(String value) {
            addCriterion("small_logo_img_url not like", value, "smallLogoImgUrl");
            return (Criteria) this;
        }

        public Criteria andSmallLogoImgUrlIn(List<String> values) {
            addCriterion("small_logo_img_url in", values, "smallLogoImgUrl");
            return (Criteria) this;
        }

        public Criteria andSmallLogoImgUrlNotIn(List<String> values) {
            addCriterion("small_logo_img_url not in", values, "smallLogoImgUrl");
            return (Criteria) this;
        }

        public Criteria andSmallLogoImgUrlBetween(String value1, String value2) {
            addCriterion("small_logo_img_url between", value1, value2, "smallLogoImgUrl");
            return (Criteria) this;
        }

        public Criteria andSmallLogoImgUrlNotBetween(String value1, String value2) {
            addCriterion("small_logo_img_url not between", value1, value2, "smallLogoImgUrl");
            return (Criteria) this;
        }

        public Criteria andLogoImgUrlIsNull() {
            addCriterion("logo_img_url is null");
            return (Criteria) this;
        }

        public Criteria andLogoImgUrlIsNotNull() {
            addCriterion("logo_img_url is not null");
            return (Criteria) this;
        }

        public Criteria andLogoImgUrlEqualTo(String value) {
            addCriterion("logo_img_url =", value, "logoImgUrl");
            return (Criteria) this;
        }

        public Criteria andLogoImgUrlNotEqualTo(String value) {
            addCriterion("logo_img_url <>", value, "logoImgUrl");
            return (Criteria) this;
        }

        public Criteria andLogoImgUrlGreaterThan(String value) {
            addCriterion("logo_img_url >", value, "logoImgUrl");
            return (Criteria) this;
        }

        public Criteria andLogoImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("logo_img_url >=", value, "logoImgUrl");
            return (Criteria) this;
        }

        public Criteria andLogoImgUrlLessThan(String value) {
            addCriterion("logo_img_url <", value, "logoImgUrl");
            return (Criteria) this;
        }

        public Criteria andLogoImgUrlLessThanOrEqualTo(String value) {
            addCriterion("logo_img_url <=", value, "logoImgUrl");
            return (Criteria) this;
        }

        public Criteria andLogoImgUrlLike(String value) {
            addCriterion("logo_img_url like", value, "logoImgUrl");
            return (Criteria) this;
        }

        public Criteria andLogoImgUrlNotLike(String value) {
            addCriterion("logo_img_url not like", value, "logoImgUrl");
            return (Criteria) this;
        }

        public Criteria andLogoImgUrlIn(List<String> values) {
            addCriterion("logo_img_url in", values, "logoImgUrl");
            return (Criteria) this;
        }

        public Criteria andLogoImgUrlNotIn(List<String> values) {
            addCriterion("logo_img_url not in", values, "logoImgUrl");
            return (Criteria) this;
        }

        public Criteria andLogoImgUrlBetween(String value1, String value2) {
            addCriterion("logo_img_url between", value1, value2, "logoImgUrl");
            return (Criteria) this;
        }

        public Criteria andLogoImgUrlNotBetween(String value1, String value2) {
            addCriterion("logo_img_url not between", value1, value2, "logoImgUrl");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andSysFlagIsNull() {
            addCriterion("sys_flag is null");
            return (Criteria) this;
        }

        public Criteria andSysFlagIsNotNull() {
            addCriterion("sys_flag is not null");
            return (Criteria) this;
        }

        public Criteria andSysFlagEqualTo(Byte value) {
            addCriterion("sys_flag =", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagNotEqualTo(Byte value) {
            addCriterion("sys_flag <>", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagGreaterThan(Byte value) {
            addCriterion("sys_flag >", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagGreaterThanOrEqualTo(Byte value) {
            addCriterion("sys_flag >=", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagLessThan(Byte value) {
            addCriterion("sys_flag <", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagLessThanOrEqualTo(Byte value) {
            addCriterion("sys_flag <=", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagIn(List<Byte> values) {
            addCriterion("sys_flag in", values, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagNotIn(List<Byte> values) {
            addCriterion("sys_flag not in", values, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagBetween(Byte value1, Byte value2) {
            addCriterion("sys_flag between", value1, value2, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagNotBetween(Byte value1, Byte value2) {
            addCriterion("sys_flag not between", value1, value2, "sysFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vedio_category
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 20 15:49:09 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}