package org.yuexin.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yuexin.model.PlayRecord;
import org.yuexin.model.PlayRecordExample;

public interface PlayRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play_record
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    int countByExample(PlayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play_record
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    int deleteByExample(PlayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play_record
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play_record
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    int insert(PlayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play_record
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    int insertSelective(PlayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play_record
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    List<PlayRecord> selectByExample(PlayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play_record
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    PlayRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play_record
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    int updateByExampleSelective(@Param("record") PlayRecord record, @Param("example") PlayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play_record
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    int updateByExample(@Param("record") PlayRecord record, @Param("example") PlayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play_record
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    int updateByPrimaryKeySelective(PlayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play_record
     *
     * @mbggenerated Tue Dec 20 14:04:37 CST 2016
     */
    int updateByPrimaryKey(PlayRecord record);
}