package org.yuexin.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yuexin.model.VedioCategory;
import org.yuexin.model.VedioCategoryExample;

public interface VedioCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    int countByExample(VedioCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    int deleteByExample(VedioCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    int insert(VedioCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    int insertSelective(VedioCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    List<VedioCategory> selectByExample(VedioCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    VedioCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    int updateByExampleSelective(@Param("record") VedioCategory record, @Param("example") VedioCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    int updateByExample(@Param("record") VedioCategory record, @Param("example") VedioCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    int updateByPrimaryKeySelective(VedioCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_category
     *
     * @mbggenerated Tue Dec 20 15:49:09 CST 2016
     */
    int updateByPrimaryKey(VedioCategory record);
}