package org.yuexin.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yuexin.model.VedioLog;
import org.yuexin.model.VedioLogExample;

public interface VedioLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_log
     *
     * @mbggenerated Wed Dec 14 10:02:02 CST 2016
     */
    int countByExample(VedioLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_log
     *
     * @mbggenerated Wed Dec 14 10:02:02 CST 2016
     */
    int deleteByExample(VedioLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_log
     *
     * @mbggenerated Wed Dec 14 10:02:02 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_log
     *
     * @mbggenerated Wed Dec 14 10:02:02 CST 2016
     */
    int insert(VedioLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_log
     *
     * @mbggenerated Wed Dec 14 10:02:02 CST 2016
     */
    int insertSelective(VedioLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_log
     *
     * @mbggenerated Wed Dec 14 10:02:02 CST 2016
     */
    List<VedioLog> selectByExample(VedioLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_log
     *
     * @mbggenerated Wed Dec 14 10:02:02 CST 2016
     */
    VedioLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_log
     *
     * @mbggenerated Wed Dec 14 10:02:02 CST 2016
     */
    int updateByExampleSelective(@Param("record") VedioLog record, @Param("example") VedioLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_log
     *
     * @mbggenerated Wed Dec 14 10:02:02 CST 2016
     */
    int updateByExample(@Param("record") VedioLog record, @Param("example") VedioLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_log
     *
     * @mbggenerated Wed Dec 14 10:02:02 CST 2016
     */
    int updateByPrimaryKeySelective(VedioLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedio_log
     *
     * @mbggenerated Wed Dec 14 10:02:02 CST 2016
     */
    int updateByPrimaryKey(VedioLog record);
}